# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 950933e842c5ba06960287e4352cb2b52cf4c2032664730a8e2db66658e5993bcc02632e44d09bfe6abb7851e1ddec136a3c712d832d6fa258c9ee5ea4a47806

test:
  secret_key_base: 1ff0bc3f28083002c52f01e84c3820d9d4eb6a13c1a60d503e84498daef1c5b8e4bfca3b726848e2698bd8f5596f7f319b4e7f331f7fe8e07e51a7acd5952688

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
